# Rafael Andreolli Prochnow RA:176059

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Tabela apresentada 
d = {'Alternativas': ['A1', 'A2', 'A3'],
     'G1': [25, 54, 15],
     'G2': [25, 17, 5], 
     'G3': [50, 71, 19],
     'G4': [75, 45, 9],
     'G5': [75, 63, 23]
    }
# Critério
crit_max = [True, True, True, True, True]
frame = pd.DataFrame(data=d)
# Pesos: w
w = [0.2, 0.2, 0.2, 0.2, 0.2]

In [3]:
frame

Alternativas  G1  G2  G3  G4  G5
0           A1  25  25  50  75  75
1           A2  54  17  71  45  63
2           A3  15   5  19   9  23

In [4]:
j = {'Perfis': ['R1', 'R2', 'R3', 'R4', 'R5'],
     'G1': [100, 75, 50, 25, 0],
     'G2': [100, 75, 50, 25, 0], 
     'G3': [100, 75, 50, 25, 0],
     'G4': [100, 75, 50, 25, 0],
     'G5': [100, 75, 50, 25, 0]
    }
perfis = pd.DataFrame(data=j)
perfis

Perfis   G1   G2   G3   G4   G5
0     R1  100  100  100  100  100
1     R2   75   75   75   75   75
2     R3   50   50   50   50   50
3     R4   25   25   25   25   25
4     R5    0    0    0    0    0

In [5]:
def flowshort(frame, perfis, w, alternativa):
    Criterios = []
    # Variação x conforme as alternativas e os critérios
    for x in range(len(w)):
        # Pegamos os valores da matriz de decisão e valores dos perfis 
        dados1 = [np.array(frame[frame.columns[1:]])[alternativa][x] for i in range(len(perfis))]
        dados = np.array(perfis[perfis.columns[1:]])
        dados = np.vstack((dados, dados1)).T
        
        tamanho = len(dados)+1
        Tabelas = np.zeros((tamanho, tamanho), dtype = int)
        # Criando a tabela de R para cada critério 
        for i in range(tamanho):
            for j in range(tamanho):
                if j>i:
                    if dados[0][i] - dados[i][j] > 0:
                        Tabelas[i,j] = 1
                    else:
                        Tabelas[i,j] = 0
                elif j<i:
                    if dados[j][i] - dados[0][j] > 0:
                        Tabelas[i,j] = 1
                    else:
                        Tabelas[i,j] = 0
        # Depois que realizar o primeiro modelo, rodamos para os demais critérios de R e acrescentamos na
        # Variável Critérios
        Criterios.append(Tabelas)
    
    # Grau de Preferência 
    for y in range(len(w)):
        Criterios[y] = Criterios[y]*w[y]
    matriz_final = sum(Criterios)

    # Cálculos dos fluxos  
    Fluxo_Negativo = []
    Fluxo_Positivo = []
    for k in range(tamanho):
        Fluxo_Positivo.append(sum(matriz_final[k])/len(w))

    matriz_invertida = matriz_final.T
    for kk in range(tamanho):
        Fluxo_Negativo.append(sum(matriz_invertida[kk])/len(w))

    # Fluxo Líquido
    Fluxo_Liquido = list(np.array(Fluxo_Positivo) - np.array(Fluxo_Negativo))
    
    # Valores finais 
    valor1 = matriz_final[-1][:-1]
    valor2 = matriz_invertida[-1][:-1]
    
    return matriz_final, Fluxo_Positivo, Fluxo_Negativo, Fluxo_Liquido, valor1, valor2

In [6]:
matriz_final, Fluxo_Positivo, Fluxo_Negativo, Fluxo_Liquido, valor1, valor2 = flowshort(frame, perfis, w, alternativa=0)

In [7]:
Fluxo_Negativo

[0.0, 0.2, 0.48, 0.72, 1.0, 0.4]

In [8]:
Fluxo_Positivo

[1.0, 0.72, 0.48, 0.2, 0.0, 0.4]

In [9]:
Fluxo_Liquido

[1.0, 0.52, 0.0, -0.52, -1.0, 0.0]

In [10]:
matriz_final

array([[0. , 1. , 1. , 1. , 1. , 1. ],
       [0. , 0. , 1. , 1. , 1. , 0.6],
       [0. , 0. , 0. , 1. , 1. , 0.4],
       [0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.4, 0.6, 1. , 0. ]])

In [11]:
valor1

array([0. , 0. , 0.4, 0.6, 1. ])

In [12]:
valor2

array([1. , 0.6, 0.4, 0. , 0. ])

In [13]:
matriz_final, Fluxo_Positivo, Fluxo_Negativo, Fluxo_Liquido, valor3, valor4 = flowshort(frame, perfis, w, alternativa=1)

In [14]:
valor3

array([0. , 0. , 0.6, 0.8, 1. ])

In [15]:
valor4

array([1. , 1. , 0.4, 0.2, 0. ])

In [16]:
matriz_final, Fluxo_Positivo, Fluxo_Negativo, Fluxo_Liquido, valor5, valor6 = flowshort(frame, perfis, w, alternativa=2)

In [17]:
valor5

array([0., 0., 0., 0., 1.])

In [18]:
valor6

array([1., 1., 1., 1., 0.])

Após realizar o método FlowSort, foram obtidos os resultados do Fluxo Negativo, Positivo, Líquido e as matrizes do grau de preferência. Não entendi direito como chegar aos valores de categoria, mas não acho que seja difícil chegar na classificação utilizando o programa.  