FCA - UNICAMP

Disciplina: PO-460 e ER-460

Introdução ao método **AHP**

In [1]:
#Importando os pacotes do Python que serão utilizados
import numpy as np  # pacote numpy importado com o apelido de np
import cmath # pacote cmath faz operações com numeros complexos

In [1]:
#Matriz de comparação par a par entre os critérios
C=[[1,1, 3],[1, 1, 1/7],[1/3,7,1]] # matriz 
print(C) #imprime a matriz para ver se ele ta sabendo

[[1, 1, 3], [1, 1, 0.14285714285714285], [0.3333333333333333, 7, 1]]


In [2]:
len(C)

3

In [3]:
#Cálculo do autovalor e do autorvetor de C
autovalor, autovetor = np.linalg.eig(C)
print(autovalor)
print(".....")
print(autovetor)


[ 4.1213843 +0.j         -0.56069215+2.07539875j -0.56069215-2.07539875j]
.....
[[-0.7111869 +0.j          0.7111869 +0.j          0.7111869 -0.j        ]
 [-0.25777689+0.j         -0.12888845-0.22324134j -0.12888845+0.22324134j]
 [-0.65403691+0.j         -0.32701845+0.56641258j -0.32701845-0.56641258j]]


In [4]:
#Considerar apenas a parte real do autovalor
autovalor_real = autovalor.real
autovetor = autovetor.real
print(autovalor_real)
print(" ")
print(autovetor.real)

[ 4.1213843  -0.56069215 -0.56069215]
 
[[-0.7111869   0.7111869   0.7111869 ]
 [-0.25777689 -0.12888845 -0.12888845]
 [-0.65403691 -0.32701845 -0.32701845]]


In [5]:
#Encontrar o maior autovalor e sua posição
lambda_max = np.amax(autovalor_real) # maior autovalor
lambda_ind = np.argmax(autovalor_real) # posição do maior autovalor
print("O maior autovalor (lambda_max) é:", lambda_max)
print(" ")
print("Ele está na posição:", lambda_ind, "do vetor")

O maior autovalor (lambda_max) é: 4.121384300715419
 
Ele está na posição: 0 do vetor


In [6]:
#Calculando o vetor de prioridades, com base no autovetor associado ao maior autovalor
vetor_P=autovetor[:, lambda_ind] #pega o autovalor correspondente a lambda_max
print(vetor_P)

#Normalizando o vetor_P para que tenha soma 1
vetor_P = vetor_P/sum(vetor_P) # w é o vetor de pesos normalizado
print(" ")
print(vetor_P)
print(sum(vetor_P))

[-0.7111869  -0.25777689 -0.65403691]
 
[0.4381926  0.15882734 0.40298005]
0.9999999999999999


In [7]:
#Calculo da consistência da matriz de comparação par a par
RI_list = [0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45] # valores de RI pré-definidos
n = len(C) # número de linhas de C
CI = (lambda_max - n)/(n-1)
RC = CI/RI_list[n-1]

print("A razão de consistência é ", RC)
print(" ")
if RC <= 0.1:
  print("A matriz é consistente")
else:
  print('\033[91m'+"Atenção:"+'\033[0m'+ "a matriz NÃO É consistente - revisar a comparação par-a-par.")


A razão de consistência é  0.9667106040650162
 
Atenção:a matriz NÃO É consistente - revisar a comparação par-a-par.


In [8]:
#Programando o método do autovalor como uma função
def ahp(C):
  autovalor, autovetor=np.linalg.eig(C)
  autovalor_real = autovalor.real
  autovetor = autovetor.real
  lambda_max = np.amax(autovalor_real) # maior autovalor
  lambda_ind=np.argmax(autovalor_real) # posição do maior autovalor
  vetor_P=autovetor[:, lambda_ind] #pega o autovalor correspondente a lambda_max
  vetor_P = vetor_P/sum(vetor_P) # w é o vetor de pesos normalizado
  RI_list = [0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45] # valores de RI pré-definidos
  n = len(C) # número de linhas de C
  CI = (lambda_max - n)/(n-1)
  RC = CI/RI_list[n-1]
  print("A razão de consistência é ", RC)
  print(" ")
  if RC <= 0.1:
    print("A matriz é consistente")
  else:
    print('\033[91m'+"Atenção:"+'\033[0m'+ "a matriz NÃO É consistente - revisar a comparação par-a-par.")
  print(" ")
  print("O vetor de prioridades é v:", vetor_P)
  print(" ")
  return vetor_P


In [9]:
A=[[1,0.2, 0.14, 0.11],[5,1,0.2,0.14],[7,5,1,0.11], [9,7,9,1]]
aa=ahp(A)

A razão de consistência é  0.2571252816185151
 
Atenção:a matriz NÃO É consistente - revisar a comparação par-a-par.
 
O vetor de prioridades é v: [0.03232434 0.08047236 0.1908988  0.6963045 ]
 


In [20]:
preco=np.array([[1,0.2, 0.14, 0.11],[5,1,0.2,0.14],[7,5,1,0.11], [9,7,9,1]])

In [22]:
preco.shape

(4, 4)

In [11]:
ahp(preco)

A razão de consistência é  0.2571252816185151
 
Atenção:a matriz NÃO É consistente - revisar a comparação par-a-par.
 
O vetor de prioridades é v: [0.03232434 0.08047236 0.1908988  0.6963045 ]
 


array([0.03232434, 0.08047236, 0.1908988 , 0.6963045 ])

In [12]:
#Após calcular todos os vetores de prioridade, a agregação pode ser feita multiplicando as matrizes B pelo vetor de pesos w
B = [[1,1,1,1],[1,1,1,1],[1,1,1,1]]
B=np.transpose(B)
w = [0.55842454, 0.31961826, 0.12195719]
V=np.matmul(B, w)
print(V)

[0.99999999 0.99999999 0.99999999 0.99999999]
